package vwap;

/**
 * ProjectEuler
 * <p>
 * Created by chenxili on 08/12/2016.
 */
public enum Instrument {
    INSTRUMENT0,
    INSTRUMENT1,
    INSTRUMENT2,
    INSTRUMENT3,
    INSTRUMENT4,
    INSTRUMENT5,
    INSTRUMENT6,
    INSTRUMENT7,
    INSTRUMENT8,
    INSTRUMENT9,
    INSTRUMENT10,
    INSTRUMENT11,
    INSTRUMENT12,
    INSTRUMENT13,
    INSTRUMENT14,
    INSTRUMENT15,
    INSTRUMENT16,
    INSTRUMENT17,
    INSTRUMENT18,
    INSTRUMENT19
}
